# <a id='toc1_'></a>[Numpy](#toc0_)

**Table of contents**<a id='toc0_'></a>    
- [Numpy](#toc1_)    
    - [Array with Random numbers](#toc1_1_1_)    
    - [Row-wise and Column-wise (```axis=```)](#toc1_1_2_)    
    - [Normalization](#toc1_1_3_)    
    - [Linear Algebra with NumPy](#toc1_1_4_)    
    - [Matrix Multiplication / Dot Product](#toc1_1_5_)    
    - [Structured Arrays](#toc1_1_6_)    
    - [What is ```data['x'][:, np.newaxis]```](#toc1_1_7_)    
    - [Masked Arrays](#toc1_1_8_)    
    - [Manual Masking](#toc1_1_9_)    
    - [Filling masked values](#toc1_1_10_)    
    - [Array with Random numbers](#toc1_1_11_)    
    - [Row-wise and Column-wise (```axis=```)](#toc1_1_12_)    
    - [Normalization](#toc1_1_13_)    
    - [Linear Algebra with NumPy](#toc1_1_14_)    
    - [Matrix Multiplication / Dot Product](#toc1_1_15_)    
    - [Structured Arrays](#toc1_1_16_)    
    - [What is ```data['x'][:, np.newaxis]```](#toc1_1_17_)    
    - [Masked Arrays](#toc1_1_18_)    
    - [Manual Masking](#toc1_1_19_)    
        - [Filling masked values](#toc1_1_19_1_1_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

***

In [ ]:
import numpy as np
import numpy.ma as ma

In [120]:
# Assi 1.1
arr1 = np.arange(1,26).reshape(5,5)
arr1

#? .reshape() is not inplace, you have to reassign 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [121]:
# Assi 1.2
arr1 = np.arange(1,17).reshape(4,4)
np.fill_diagonal(arr1, 0)
arr1
#? .fill_diagonal(arr, value), is inplace

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

In [122]:
# Assi 2.1
arr2 = np.arange(1,37).reshape(6,6)
print(arr2)
arr2[2:5,1:4]


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

***

### <a id='toc1_1_11_'></a>[Array with Random numbers](#toc0_)

In [123]:
float_array_1d = np.random.rand(5)

float_array_2d = np.random.rand(2,6)
float_array_2d

array([[0.89176602, 0.96658365, 0.32628821, 0.41543772, 0.69497914,
        0.90366787],
       [0.37525869, 0.88503424, 0.48269476, 0.03451206, 0.24539105,
        0.4673792 ]])

In [124]:
# With Range
# np.random.randint(start, stop, size)
int_rand_1d = np.random.randint(0,10,5)

int_rand_2d = np.random.randint(1,26,(2,4))
int_rand_2d

array([[ 2, 11, 18,  9],
       [ 8, 13, 10, 17]])

***

In [125]:
# Assi 2.2
arr2 = np.random.randint(0,100, (5,5))
print(arr2)
print("~~~")
top = arr2[0]
bottom = arr2[-1]
left = arr2[:, 0]
right = arr2[:, -1]

print("top:\n",top)
print("bottom:\n",bottom)
print("left:\n",left.reshape(5,1))
print("right:\n",right.reshape(5,1))

[[ 5 36 57 83 41]
 [88 30 59 39 89]
 [78 81 60 21 31]
 [20 63 67 35 52]
 [10 41 25 84 38]]
~~~
top:
 [ 5 36 57 83 41]
bottom:
 [10 41 25 84 38]
left:
 [[ 5]
 [88]
 [78]
 [20]
 [10]]
right:
 [[41]
 [89]
 [31]
 [52]
 [38]]


In [126]:
# Assi 3.1
arr3a = np.random.randint(1,100, (3,4))
arr3b = np.random.randint(1,100, (3,4))

print("Add\n",arr3a + arr3b)
print("Subtract\n",arr3a - arr3b)
print("Multiply\n",arr3a * arr3b)
print("Divide\n",arr3a / arr3b)

Add
 [[133 154 120  67]
 [ 97  85  21 145]
 [ 56 131 165 123]]
Subtract
 [[-15   8  72  45]
 [ 61   3 -15 -13]
 [ -4  -7  15  49]]
Multiply
 [[4366 5913 2304  616]
 [1422 1804   54 5214]
 [ 780 4278 6750 3182]]
Divide
 [[0.7972973  1.10958904 4.         5.09090909]
 [4.38888889 1.07317073 0.16666667 0.83544304]
 [0.86666667 0.89855072 1.2        2.32432432]]


***

### <a id='toc1_1_12_'></a>[Row-wise and Column-wise (```axis=```)](#toc0_)

In [127]:
# axis = 1 , operation will be done with rows
# axis = 0 , operation will be done with columns
# If not provided (None by Default), element wise operation is done 

In [128]:
# Create a 2D NumPy array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Element-wise operation (e.g., squaring each element)
squared_arr = arr ** 2
print("Squared array (element-wise):\n", squared_arr)

# Row-wise sum (sum of elements in each row)
row_sums = arr.sum(axis=1)
print("\nRow sums:\n", row_sums)

# Column-wise mean (mean of elements in each column)
col_means = arr.mean(axis=0)
print("\nColumn means:\n", col_means)

Squared array (element-wise):
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]

Row sums:
 [ 6 15 24]

Column means:
 [4. 5. 6.]


***

In [129]:
# Assi 3.2
arr3 = np.random.randint(1,20,(4,4))
print(arr3)

# Row wise sum (each col is sum of all elements in each original row)
row_sums = arr3.sum(axis=1)
print("Row wise sums:\n", row_sums)
# 5 + 2 + 8 + 8 = 23

# Column wise sum
col_sums = arr3.sum(axis=0)
print("Column wise sums:\n", col_sums)
# 5 + 3 + 3 + 6 = 17

[[18 15  8 16]
 [ 2  6 15 16]
 [ 1 13 17  1]
 [ 7  9  8 15]]
Row wise sums:
 [57 39 32 39]
Column wise sums:
 [28 43 48 48]


In [130]:
# Assi 4.1
arr4 = np.random.randint(0,100, (5,5))

mean = np.mean(arr4)
median = np.median(arr4)
std_dev = np.std(arr4)
variance = np.var(arr4)

print("Mean:\n", mean)
print("median:\n", median)
print("Standard Deviation:\n", std_dev)
print("Variance:\n", variance)

Mean:
 42.76
median:
 41.0
Standard Deviation:
 27.79680557186383
Variance:
 772.6624


***

### <a id='toc1_1_13_'></a>[Normalization](#toc0_)

_To have mean = 0 and standard deviation = 1_
1. Calculate Mean and Standard Deviation
2. Normalized_Data = (data-mean)/standard_dev

***

In [131]:
# Assi 4.2
arr4 = np.arange(1,10).reshape(3,3)
print("Original Data:\n", arr4)

# Step 1
mean = np.mean(arr4)
std_dev = np.std(arr4)

# Step 2
normalized_data = (arr4 - mean)/std_dev

print("Normalized Data:\n", normalized_data)

Original Data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized Data:
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [132]:
# Assi 5.1
arr5_2d = np.random.randint(1,10, (3,3))
arr5_1d = np.random.randint(1,10,3)

print(arr5_1d)
print("---------------")
print(arr5_2d)
print("---------------")

print("Final Array:\n", arr5_2d + arr5_1d)

[8 2 8]
---------------
[[6 8 4]
 [3 9 3]
 [9 6 6]]
---------------
Final Array:
 [[14 10 12]
 [11 11 11]
 [17  8 14]]


In [133]:
# Assi 5.2
arr5_2d = np.random.randint(1,20,(4,4))
arr5_1d = np.random.randint(1,20,4)

print(arr5_1d)
print("---------------")
print(arr5_2d)
print("---------------")

print("Final Array:\n", arr5_2d - arr5_1d)

[ 3 19  3  9]
---------------
[[15  1  8 15]
 [11 14  8  2]
 [13  9  9 16]
 [16 19 12  1]]
---------------
Final Array:
 [[ 12 -18   5   6]
 [  8  -5   5  -7]
 [ 10 -10   6   7]
 [ 13   0   9  -8]]


***

### <a id='toc1_1_14_'></a>[Linear Algebra with NumPy](#toc0_)

In [137]:
matrix = np.random.randint(1,10, (3,3))


In [138]:
print("Matrix:\n",matrix)
print("---------------")

# Transpose
transpose = np.transpose(matrix)
print("Transpose:\n",transpose)
print("---------------")

# Determinant
det = np.linalg.det(matrix)
print("Determinant:\n",det)
print("---------------")

# Inverse
inv = np.linalg.inv(matrix)
print("Inverse:\n",inv)
print("---------------")

# Eigenvalues and Eigenvectors
eig = np.linalg.eig(matrix)
print("Eigenvalues and Eigenvectors:\n",eig)
print("---------------")

# Rank
rank = np.linalg.matrix_rank(matrix)
print("Rank:\n", rank)
print("---------------")

# Flatten (convert ND matrix to 1D)
flat_matrix = matrix.flatten()
print("Flatten:\n", flat_matrix)
print("---------------")

Matrix:
 [[6 6 2]
 [8 8 3]
 [4 8 3]]
---------------
Transpose:
 [[6 8 4]
 [6 8 8]
 [2 3 3]]
---------------
Determinant:
 -7.999999999999995
---------------
Inverse:
 [[ 0.    0.25 -0.25]
 [ 1.5  -1.25  0.25]
 [-4.    3.   -0.  ]]
---------------
Eigenvalues and Eigenvectors:
 EigResult(eigenvalues=array([16.35881461,  1.08988631, -0.44870092]), eigenvectors=array([[-0.49543591, -0.28370022,  0.14943249],
       [-0.67180166, -0.08617754, -0.45348931],
       [-0.55065941,  0.95503278,  0.87864519]]))
---------------
Rank:
 3
---------------
Flatten:
 [6 6 2 8 8 3 4 8 3]
---------------


***

In [ ]:
# Assi 6.1
arr6 = np.random.randint(1,10,(3,3))

In [ ]:
print("Matrix:\n", arr6)
print("---------------")

Matrix:
 [[5 2 1]
 [6 9 5]
 [6 9 8]]
---------------


In [ ]:
det = np.linalg.det(arr6)
print("Determinant:\n", det)
print("---------------")

inv = np.linalg.inv(arr6)
print("Inverse:\n", inv)
print("---------------")

eigenValues = np.linalg.eigvals(arr6)
print("EigenValues:\n", eigenValues)
print("---------------")


Determinant:
 98.99999999999999
---------------
Inverse:
 [[ 0.27272727 -0.07070707  0.01010101]
 [-0.18181818  0.34343434 -0.19191919]
 [ 0.         -0.33333333  0.33333333]]
---------------
EigenValues:
 [16.73715807  3.6361068   1.62673513]
---------------


***

### <a id='toc1_1_15_'></a>[Matrix Multiplication / Dot Product](#toc0_)

In [ ]:
np.dot(arr1, arr2)

#Preffered for 2D Matrix
np.matmul(arr1, arr2)
or
arr1 @ arr2

***

In [ ]:
# Assi 6.2
arr6_1 = np.random.randint(1,10,(2,3))
arr6_2 = np.random.randint(1,10,(3,2))

print(arr6_1 @ arr6_2)
print(np.dot(arr6_1, arr6_2))
print(np.matmul(arr6_1, arr6_2))

[[100  78]
 [ 76  66]]
[[100  78]
 [ 76  66]]
[[100  78]
 [ 76  66]]


In [ ]:
def sep():
    print("================")

In [ ]:
# Assi 7.1
arr7 = np.random.randint(1,10,(3,3))
print(arr7)
sep()

arr7 = arr7.reshape(1,9)
print(arr7)
sep()

arr7 = arr7.reshape(9,1)
print(arr7)
sep()

[[1 5 6]
 [2 4 2]
 [6 2 8]]
[[1 5 6 2 4 2 6 2 8]]
[[1]
 [5]
 [6]
 [2]
 [4]
 [2]
 [6]
 [2]
 [8]]


In [ ]:
# Assi 7.2
arr7 = np.random.randint(1,25,(5,5))
print(arr7)
sep()

arr7 = arr7.flatten()
print(arr7)
sep()

arr7 = arr7.reshape(5,5)
print(arr7)
sep()


[[ 8  7 20  3  8]
 [17 11  9 20 18]
 [ 4  1 19  1 20]
 [ 5  6 24 13 13]
 [ 8  1 19 19 10]]
[ 8  7 20  3  8 17 11  9 20 18  4  1 19  1 20  5  6 24 13 13  8  1 19 19
 10]
[[ 8  7 20  3  8]
 [17 11  9 20 18]
 [ 4  1 19  1 20]
 [ 5  6 24 13 13]
 [ 8  1 19 19 10]]


In [ ]:
# Assi 8.1
arr8 = np.random.randint(1,25,(5,5))
print(arr8)
sep()

rows = [0, 0, 4, 4]
columns = [0, 4, 0, 4]
arr8[rows, columns] # Gives (0,0), (0,4), (4,0), (4,4)

[[13  8 21 12 19]
 [ 4 22  8  7 23]
 [11 14  8 13  4]
 [14 13 12  4  9]
 [ 9 24 17 16 21]]


array([13, 19,  9, 21])

In [ ]:
# Assi 8.2
arr8 = np.random.randint(1,20, (4,4))

In [ ]:
print(arr8)
sep()

arr8[arr8>10] = 10
print(arr8)

[[17 12  3  1]
 [ 9 19  7 15]
 [10 15  4  6]
 [ 9  9 18 10]]
[[10 10  3  1]
 [ 9 10  7 10]
 [10 10  4  6]
 [ 9  9 10 10]]


***

### <a id='toc1_1_16_'></a>[Structured Arrays](#toc0_)
_Heterogenous Array_

In [ ]:
person_dtype = np.dtype([
    ("name","U10"),
    ("age", "i4"),
    ("weight", "f4")
    ])

people_arr = np.array([
    ("Alice", 25, 55.5),
    ("Bob",   30, 68.2),
    ("Charlie", 35, 72.3)
], dtype=person_dtype)

print(people_arr)
print(people_arr["name"])
print(people_arr[1])

# Sorting Structured array
print(np.sort(people_arr,order='weight'))

[('Alice', 25, 55.5) ('Bob', 30, 68.2) ('Charlie', 35, 72.3)]
['Alice' 'Bob' 'Charlie']
('Bob', 30, 68.2)
[('Alice', 25, 55.5) ('Bob', 30, 68.2) ('Charlie', 35, 72.3)]


***

In [ ]:
# Assi 9.1
person_dtype = np.dtype([
    ('name', 'U10'),
    ('age', 'i4'),
    ('weight', 'f4')
])

people_arr = np.array([
    ('dev',21,68.1),
    ('john',34,76.32),
    ('arthur',32,78.1),],
    dtype=person_dtype
)

print(people_arr)
sorted_ageArray = np.sort(people_arr, order='age')
print(sorted_ageArray)

[('dev', 21, 68.1 ) ('john', 34, 76.32) ('arthur', 32, 78.1 )]
[('dev', 21, 68.1 ) ('arthur', 32, 78.1 ) ('john', 34, 76.32)]


***
### <a id='toc1_1_17_'></a>[What is ```data['x'][:, np.newaxis]```](#toc0_)

In [ ]:
data_dtype = np.dtype([
    ('x', 'i4'),
    ('y', 'i4'),
])

data = np.array([
    (3,4),
    (7,2),
    (8,3),],
    dtype=data_dtype)

data['x'] # 1D Array
data['x'][:,np.newaxis]

#? Converted the 1D row matrix to 1D Column 
# Why do we need it
# To easily perform column operations

array([[3],
       [7],
       [8]])

***

In [ ]:
# Assi 9.2
point_dtype = np.dtype([
    ('x', 'i4'),
    ('y', 'i4'),
])

points = np.array([
    (3,4),
    (7,2),
    (8,3),],
    dtype=point_dtype)

print(points)

# Euclidean Distance =( (x2-x1)**2 + (y2-y1)**2 )**0.5
# data['x'][:,np.newaxis] - data['x'] -> difference table of all possible 'x' pairs

distances = np.sqrt(
    (data['x'][:,np.newaxis] - data['x'])**2 +
    (data['y'][:,np.newaxis] - data['y'])**2 )

print(distances)

[(3, 4) (7, 2) (8, 3)]
[[0.         4.47213595 5.09901951]
 [4.47213595 0.         1.41421356]
 [5.09901951 1.41421356 0.        ]]


***

### <a id='toc1_1_18_'></a>[Masked Arrays](#toc0_)
Numpy arrays with additional masks which tells which values are valid and which ones are hidden/masked

In [ ]:
import numpy.ma as ma

array = np.array([1,2,201,4,201,6])
print(array)
sep()

# mask the invalid value 201
masked_array = ma.masked_equal(array, 201)
print(masked_array)
sep()

print(masked_array.mean())  # Ignores 201
print(masked_array.sum())  # Ignores 201


[  1   2 201   4 201   6]
[1 2 -- 4 -- 6]
3.25
13


***

In [ ]:
# Assi 10.1
arr10 = np.random.randint(1,20, (4,4))
print(arr10)
sep()

masked_arr10 = ma.masked_greater(arr10, 10)
print(masked_arr10)

print("Sum of Unmasked Elements: ", ma.sum(masked_arr10))

[[18 11 14  7]
 [12 17 14 13]
 [ 2 14 14  1]
 [13  8 13  4]]
[[-- -- -- 7]
 [-- -- -- --]
 [2 -- -- 1]
 [-- 8 -- 4]]
Sum of Unmasked Elements:  22


***

### <a id='toc1_1_19_'></a>[Manual Masking](#toc0_)
Suppose you want to mask only the border elements of a 4x4 matrix

In [ ]:
arr_4x4 = np.random.randint(1,11,(4,4))
print(arr_4x4)
sep()
# 1 -> Masked
# 0 -> Unmasked
mask = [
    [1,1,1,1],
    [1,0,0,1],
    [1,0,0,1],
    [1,1,1,1],
]

masked_4x4 = ma.array(arr_4x4,mask=mask)
print(masked_4x4)


[[ 1 10 10  8]
 [ 4  6  7  6]
 [ 5  3  8  5]
 [ 5  6  1  9]]
[[-- -- -- --]
 [-- 6 7 --]
 [-- 3 8 --]
 [-- -- -- --]]


##### <a id='toc1_1_19_1_1_'></a>[Filling masked values](#toc0_)

In [ ]:
print(masked_4x4.filled(-1))

[[-1 -1 -1 -1]
 [-1  6  7 -1]
 [-1  3  8 -1]
 [-1 -1 -1 -1]]


***

In [ ]:
# Assi 10.2
arr10 = np.random.randint(1,10,(3,3))
print(arr10)
sep()

# Identity matrix, diagonal elements = 1
mask = np.eye(3, dtype=int)

masked10 = ma.array(arr10, mask=mask)
print(masked10)
sep()

mean = masked10.mean()
print("Mean: ", int(mean))
mask_filled = masked10.filled(mean)
print(mask_filled)
sep()

[[7 7 5]
 [9 3 8]
 [5 2 9]]
[[-- 7 5]
 [9 -- 8]
 [5 2 --]]
Mean:  6
[[6 7 5]
 [9 6 8]
 [5 2 6]]
