## L54 - Numpy

### Basics

In [1]:
import numpy as np

In [4]:
# .arange(start, stop, step)
arr1 = np.arange(0,10,2)
arr1

array([0, 2, 4, 6, 8])

In [5]:
# .reshape(row,col) 
arr1.reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [6]:
arr1.reshape(4,1)

ValueError: cannot reshape array of size 5 into shape (4,1)

In [7]:
# .ones( (row,col) )
np.ones( (4,3) )

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# .eye(size) -> Creates Identity matrix
np.eye(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### Attributes

In [10]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int32
Item size (in bytes): 4


### Vectorized operations

In [21]:
arr1 = np.arange(0,6).reshape(3,2)
arr2 = np.arange(0,12,2).reshape(3,2)

# Element wise Addition
print("Addition:\n",arr1 + arr2)

# Element wise Subtraction
print("Subtraction:\n",arr1 - arr2)

# Element wise Multiplication
print("Multiplication:\n", arr1*arr2)

# Element wise division
print("Division:\n", arr1/arr2)

Addition:
 [[ 0  3]
 [ 6  9]
 [12 15]]
Subtraction:
 [[ 0 -1]
 [-2 -3]
 [-4 -5]]
Multiplication:
 [[ 0  2]
 [ 8 18]
 [32 50]]
Division:
 [[nan 0.5]
 [0.5 0.5]
 [0.5 0.5]]


C:\Users\pdev2\AppData\Local\Temp\ipykernel_14320\4192023824.py:14: RuntimeWarning: invalid value encountered in divide
  print("Division:\n", arr1/arr2)
